version: '3.8'

services:

  wordpress:
    image: wordpress:latest
    container_name: tcc-ebac-wordpress
    ports:
      - "8000:80"  # Acessa WP no http://localhost:8000
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: password
      JWT_AUTH_SECRET_KEY: "ck_6d168c71248bdc44dc270d1c37b7bd47299a76d8"
    volumes:
      - ./wordpress:/var/www/html  # Código WP local
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: tcc-ebac-mysql
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpass  # SENHA ROOT DO MYSQL
    volumes:
      - tcc-ebac-db_data:/var/lib/mysql  # Volume explícito e nomeado para dados do MySQL

volumes:
  tcc-ebac-db_data: