name: Testes CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      USERNAME: ${{ secrets.USERNAME }}
      PASSWORD: ${{ secrets.PASSWORD }}

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependências
        run: npm install

      - name: Corrigir permissão do jest
        run: chmod +x ./node_modules/.bin/jest

      - name: Iniciar containers Docker
        run: |
          docker network create --attachable ebac-network || true
          docker run -d --name wp_db -p 3306:3306 --network ebac-network ernestosbarbosa/lojaebacdb:latest
          docker run -d --name wp -p 80:80 --network ebac-network ernestosbarbosa/lojaebac:latest

      - name: Aguardar WordPress subir
        run: sleep 30

      - name: Rodar testes de API com Jest
        run: npm run test:api

      - name: Rodar testes UI com Cypress (headless)
        run: npm run test:ui