name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cypress-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Start local server
        run: |
          docker network create --attachable ebac-network || true
          docker run -d --name wp_db -p 3306:3306 --network ebac-network ernestosbarbosa/lojaebacdb:latest
          docker run -d --name wp -p 80:80 --network ebac-network ernestosbarbosa/lojaebac:latest
        # dá um tempinho para o WP subir
      - name: Wait for server
        run: sleep 30

      - name: Run API tests
        run: npm run test:api

      - name: Run Cypress UI tests
        run: npm run test:ui